---
title: "Homework_1"
author: "Shadman Amin & Lily Heidger"
format: 
  html:
    code-fold: show
    toc: true
    embed-resources: true
editor: visual
theme: lumen
execute:
  echo: true
  message: false
  warning: false
---
# Homework 1

```{r, setup}
library(dplyr)
library(here)
library(readr)
library(tidyverse)

algae <- read_table("algaeBloom.txt", col_names= c('season', 'size', 'speed', 'mxPH', 'mnO2', 'Cl', 'NO3', 'NH4', 'oPO4','PO4','Chla','a1','a2','a3','a4','a5','a6','a7'),
                     na="XXXXXXX")
glimpse(algae)
```

## 1 Descriptive Summary Statistics
### a) 
```{r}
algae %>% group_by(season) %>% summarise(length(size))
```
### b) Yes, there are 33 missing values. 
```{r}
na_count <-sapply(algae, function(y) sum(length(which(is.na(y)))))

data.frame(na_count)
sum(na_count)

mean(algae$mxPH)

means <- sapply(algae, function(q) mean())

summarise(algae, mean = mean(mxPH, mnO2, Cl, NO3, NH4, oPO4, PO4, Chla))


chemicals <- algae %>% select(mxPH, mnO2, Cl, NO3, NH4, oPO4, PO4, Chla)
colMeans(chemicals,)
```


## 4. a)

## 5. 

Bias()